version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: air_quality_postgres
    restart: always
    environment:
      POSTGRES_USER: monitor_user
      POSTGRES_PASSWORD: monitor_password
      POSTGRES_DB: air_quality_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:7-alpine
    container_name: air_quality_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: